source 'https://rubygems.org'

gem 'cocoapods', '~> 1.16'
gem 'fastlane'

# Ruby 3.4+ stdlib compatibility
gem 'abbrev'
gem 'base64'
gem 'bigdecimal'
gem 'logger'
gem 'mutex_m'
gem 'ostruct'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
