require 'dotenv'
require_relative '../../fastlane/Fasthelper'

Dotenv.load('../../fastlane/.env')

default_platform(:android)

def validate_distribution_files(apk_path:, service_credentials_file:)
  SharedFastlane.validate_file_exists(
    file_path: apk_path,
    file_name: 'APK file'
  )
  SharedFastlane.validate_file_exists(
    file_path: service_credentials_file,
    file_name: 'Firebase service account credentials file'
  )
end

def upload_to_firebase_distribution(app_id:, tester_groups:, service_account_name:, apk_relative_path:)
  service_account_path = SharedFastlane.service_account_path(file_name: service_account_name, fastfile_dir: __dir__)
  apk_path = SharedFastlane.get_apk_path(relative_path: apk_relative_path, fastfile_dir: __dir__)

  validate_distribution_files(
    apk_path: apk_path,
    service_credentials_file: service_account_path
  )
  firebase_app_distribution(
    app: app_id,
    apk_path: apk_path,
    groups: tester_groups,
    service_credentials_file: service_account_path
  )
end

platform :android do
  desc 'Clean project'
  lane :flutter_clean do
    UI.message('Cleaning Flutter project...')
    sh 'flutter clean'
    UI.success('Flutter project cleaned successfully! 🎉')
  end

  desc 'Build release AAB'
  lane :build_release_aab do
    flutter_clean

    UI.message('Building release AAB...')
    sh 'flutter build appbundle --release'

    UI.success('Release AAB built successfully 🎉')
  end

  desc 'Build release APK'
  lane :build_release_apk do
    flutter_clean

    UI.message('Building release APK...')
    sh 'flutter build apk --release'

    UI.success('Release APK built successfully 🎉')
  end

  desc 'Upload to Firebase App Distribution'
  lane :distribute_to_firebase do
    build_release_apk

    UI.message('Uploading APK to Firebase App Distribution...')

    upload_to_firebase_distribution(
      app_id: ENV.fetch('FIREBASE_APP_ID'),
      tester_groups: ENV.fetch('TESTER_GROUP'),
      service_account_name: ENV.fetch('SERVICE_ACCOUNT_NAME'),
      apk_relative_path: 'apk/release/app-release.apk'
    )

    UI.success('APK uploaded to Firebase App Distribution successfully 🎉')
  end
end
