name: "[Android-Prod] Deploy to Firebase App Distribution"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Android-Prod
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
          
      - name: Create secrets
        working-directory: android
        run: |
          mkdir -p fastlane/service_account/
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/google-services.json
          echo "$SERVICE_ACCOUNT_JSON_PROD" | base64 -d > fastlane/service_account/test-project-d9d3e-1ef79b14b4f6.json
          echo "$KEYSTORE" | base64 -d > key_prod.jks
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          SERVICE_ACCOUNT_JSON_PROD: ${{ secrets.SERVICE_ACCOUNT_JSON_PROD }}
          KEYSTORE: ${{ secrets.KEYSTORE }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          working-directory: android
          bundler-cache: true

      - name: Deploy to Firebase app distribution
        working-directory: android

        run: bundle exec fastlane distribute_to_firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          TESTER_GROUP: ${{ secrets.TESTER_GROUPS }}
          CM_KEYSTORE_PATH: ${{ github.workspace }}/android/key_prod.jks
          CM_KEYSTORE_PASSWORD: ${{ secrets.CM_KEYSTORE_PASSWORD }}
          CM_KEY_ALIAS: ${{ secrets.CM_KEY_ALIAS }}
          CM_KEY_PASSWORD: ${{ secrets.CM_KEY_PASSWORD }}
